# Generated by Django 5.1.5 on 2025-02-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_food_gadget_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gadget',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
